apiVersion: v1
kind: Secret
metadata:
  name: ai-workflow-secret
  namespace: ai-workflow
type: Opaque
stringData:
  JWT_SECRET: "replace-this"
  DEMO_USER_EMAIL: "admin@example.com"
  DEMO_USER_PASSWORD: "replace-this"
  S3_ACCESS_KEY_ID: "replace-this"
  S3_SECRET_ACCESS_KEY: "replace-this"
  OPENSEARCH_USER: "replace-this"
  OPENSEARCH_PASSWORD: "replace-this"
